name: CI #自动化的名称
on:
  push: # push的时候触发
    branches: # 那些分支需要触发
      - main
  workflow_dispatch:    

# 关键步骤：设置权限
permissions:
  contents: write # 允许写入代码仓库内容
  pages: write    # 允许写入 Pages 内容
  id-token: write # 允许 OIDC 认证 (新版 Pages 部署需要)


jobs:
  build:
    runs-on: ubuntu-latest # 镜像市场
    steps:
      - name: checkout # 步骤的名称
        uses: actions/checkout@v2.3.4 #软件市场的名称
        with: # 参数
          submodules: true
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: 0.145.0
          extended: true
      - name: Build
        run: hugo -D
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          EXTERNAL_REPOSITORY: fengzhao/hugo-blog # 注意要修改本处地址
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public
